### ISSUE TITLE
'Allow newlines' option

### ISSUE THREAD

**Issue by cohix** [mathiasbynens/jsesc#20]
jsesc should have an option to allow newline characters:
```
var escaped = jsesc(string, {newlinesAllowed: true} );
```
So if the string contains a newline character (`\n`), it would not be replaced by `\\n`

**Comment by mathiasbynens** [comment]
What’s your use case exactly?

**Comment by cohix** [comment]
I have a field in my database that I want to allow real newline characters.

**Comment by mathiasbynens** [comment]
For now this can be solved with:

```js
var escaped = string.split('\n').map(function(line) {
  return jsesc(line);
}).join('\n');
```

I’m worried that this is not common enough to extend the API for. Also, `allowNewlines` seems like too specific an option. If we decide to add something like this, maybe add a `whitelist` property instead?

**Comment by cohix** [comment]
Yeah I like the whitelist idea. Good call.
