### ISSUE TITLE
How to revert back escaped string

### ISSUE THREAD

**Issue by bcalik** [mathiasbynens/jsesc#24]
Is there any way to revert back the escaped string?

**Comment by michaelficarra** [comment]
`eval`?

**Comment by bcalik** [comment]
Sorry I am really not a javascript guy. Could you please give an example? I could not do it.

**Comment by michaelficarra** [comment]
```js
eval(x)
```

**Comment by bcalik** [comment]
`eval` gives me an error.

This one solved my issue, thank you anyway:
```javascript
var decodedString = JSON.parse("\""+encodedString+"\"").toString();
```
