### ISSUE TITLE
missing = in const declaration

### ISSUE THREAD

**Issue by Akkuma** [mathiasbynens/jsesc#33]
https://github.com/mathiasbynens/jsesc/blob/30be7a62d862d8b5b49ffc4424a10c85f0ee6f6d/src/jsesc.js#L6 causes Firefox to throw the above error, which can be reproduced by pasting this into Firefox's console.

```js
for (const key in {t:1,x:1}) {
  if (hasOwnProperty.call(object, key)) {
    console.log('Never reaches as the code errors');
  }
}
```

This makes jsesc unusable with webpack/browserify in those environments without explicitly converting the es6 code into es5.

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/jsesc#support
