### ISSUE TITLE
Discrepancy between published version and Github version

### ISSUE THREAD

**Issue by cerebrl** [mathiasbynens/jsesc#35]
Hello Mathias, thanks for this great tool! I did find a discrepancy between what is currently published on NPM and what's on Github. When I install the latest from NPM, which seems to be 2.2.0 (verified on the module's `package.json`), I get the 2.1.0 version of `jsesc.js` (it's both missing the change to `isScriptContext` and also has the version of 2.1.0 as the value for `jsesc.version`).

Am I missing something, or was there just a mixup? Thanks in advance for any help.

**Comment by mathiasbynens** [comment]
The `isScriptContext` change was made after v2.2.0. 

I hadn’t published a new version containing this change, though, so I’ve fixed that now: v2.3.0 Thanks for the reminder!
