### ISSUE TITLE
`none` mode

### ISSUE THREAD

**Issue by kdex** [mathiasbynens/jsesc#41]
Hi Mathias!

One of my projects requires me to have a binary blob (synchronously) ready at `require` time. Hence, part of the build pipeline is to load the blob into a string (in the build step) and then read the string and convert it to a `TypedArray` during runtime.
 
When running the bundle through babel, the `119 KiB` blob and `64 KiB` source sum up to `408 KiB` (after minification). One might have (very rougly) expected a total of around `64 KiB + 119 KiB = 183 KiB`.

The problem is that most of the blob, which is part of the bundle, is now escaped, which takes up a lot of space. This limitation seems to be known and has been mentioned [in this discussion](https://github.com/babel/babel/issues/4909) already.

I see you've implemented a `minimal` mode which only escapes very few characters. Since my payload contains a good amount of null bytes, this wouldn't help me a lot. My best option would be to specify an option such as `none` (feel free to bikeshed!), once babel allows passing options to `jsesc`.

Such an option would not touch any string and just act as an identity function, so to say. Maybe `disabled` or `nothing` are better names.

Would you be willing to add such a mode, please?

**Comment by michaelficarra** [comment]
Asking a dependency for an option which effectively disables it so that the consuming application doesn't need to avoid calling it seems inappropriate. Just have babel not call jsesc.

**Comment by kdex** [comment]
@michaelficarra Oh, yes, that sounds a lot better. When I wrote this, I had these "do nothing by default" tools (like some minifiers or transpilers) in mind, which is a slightly different story. Thanks for the guidance!
