### ISSUE TITLE
Usage of string.prototype.repeat breaks IE11

### ISSUE THREAD

**Issue by smonusbonus** [mathiasbynens/jsesc#46]
When using jsesc inside the browser context the usage of string.prototype.repeat breaks IE11. It results in a ```TypeError: Object doesn't support property or method 'repeat'```. Is it a conscious decision not to support ES5/IE11 with this library? I think a polyfill or transpilation to ES5 Javascript would solve the problem ...

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/jsesc#support

**Comment by mathiasbynens** [comment]
Sounds like you want `npm i jsesc@1.3.0`.
