### ISSUE TITLE
indent option only is valid when compact is false (!true)

### ISSUE THREAD

**Issue by caseman72** [mathiasbynens/jsesc#53]
This:
> The indent option takes a string value, and defaults to '\t'. When the compact setting is **enabled (true)**, the value of the indent option is used to format the output for arrays and objects.

Should be:
> The indent option takes a string value, and defaults to '\t'. When the compact setting is **disabled (false)**, the value of the indent option is used to format the output for arrays and objects.

Link:
https://github.com/mathiasbynens/jsesc#indent

**Comment by mathiasbynens** [comment]
Good catch, thanks! Do you want to submit a pull request?
