### ISSUE TITLE
Check for existence of Buffer

### ISSUE THREAD

**Issue by isidrok** [mathiasbynens/jsesc#63]
Hi, I'm using this library inside of a service worker and as there is no Buffer implementation I have to polyfill it although it will never be used.

It would be great if `isBuffer` checked for the existence of `Buffer` so the library can be used without problems in environments that don't support it:

```js
// current
const isBuffer = Buffer.isBuffer;

// proposal
const isBuffer = (value) => typeof Buffer !== 'undefined' && Buffer.isBuffer(value)
```

Can submit a PR if interested in the change.

**Comment by mathiasbynens** [comment]
Yes please submit a PR!
