### ISSUE TITLE
feature: use backticks as string delimiter

### ISSUE THREAD

**Issue by milahu** [mathiasbynens/jsesc#65]
input
```
var s = "some 'thing' ${here}"
```
expected
```
`var s = "some 'thing' $\{here}"`
```
actual
```
'var s = "some \'thing\' ${here}"'
```
goal: minimize number of escapes

edit: i was looking for node's [util.inspect(object)](https://nodejs.org/api/util.html#util_util_inspect_object_options)

```node
> console.log(u.inspect(`var s = "some 'thing' here"`))
`var s = "some 'thing' here"`

> console.log(u.inspect(`var s = "some 'thing' $\{here}"`))
'var s = "some \'thing\' ${here}"'
```

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/jsesc#quotes

**Comment by milahu** [comment]
aah, sorry. i got distracted by [the demo](https://mothereff.in/js-escapes) where the `quotes` option is not exposed
